version: 2
jobs:
  build:
    省略
  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - set_up_docker
      - run:
        name: install aws cli
        command: |
          apk add --no-cache --update py-pip
          pip install awscli
      - run:
        name: build image
        command: |
          $(aws ecr get-login --no-include-email --region ap-northeast-1)
          docker build -t ${ECR_DOMAIN}/s a m p l e - i m a g e : $ C I R C L E _ S H A
1 - t ${ECR_DOMAIN}/sample-image:latest - - b u i l d - a r g R A I L S _ M A S T E R _ K E Y
=${RAILS_MASTER_KEY} --build-arg RAILS_ENV=production .
      - run:
        name: Push docker image
        command: |
          docker push ${ECR_DOMAIN}/sample-image:$CIRCLE_SHA1
          docker push ${ECR_DOMAIN}/sample-image:latest
workflows:
    version: 2
    test:
      jobs:
        - build
        - build_image:
          requires:
            - build
          filters:
            branches:
              only: master