default: &default
  adapter: mysql2
  encoding: utf8
  database: rails_tutorial
  username: root
  password:
  host: 127.0.0.1

development:
  adapter: mysql2
  encoding: utf8
  database: rails_tutorial
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *default
#  database: db/test.sqlite3

production:
  <<: *default
#  database: db/production.sqlite3
